Repository alyssabull/rancid-tomatillos, pull requests merged in 2020-12, with the labels that each got.

#3 Main Poster Display
  .eslintcache
  src/App.js
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/MovieContainer/MovieContainer.css
  src/Components/MovieContainer/MovieContainer.js
  src/Components/MovieContainer/MovieContainer.test.js
  src/Components/MoviePoster/MoviePoster.css
  src/Components/MoviePoster/MoviePoster.js
  src/Components/MoviePoster/MoviePoster.test.js
  src/SampleMovieData.js
  src/index.js
Labels: DOM, New component

#4 Style movie posters and movie container
  .eslintcache
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/MovieContainer/MovieContainer.css
  src/Components/MoviePoster/MoviePoster.css
  src/Components/MoviePoster/MoviePoster.js
Labels: DOM, enhancement

#8 Movie detail view and information
  .eslintcache
  src/Components/App/App.js
  src/Components/MovieContainer/MovieContainer.js
  src/Components/MovieDetails/MovieDetails.css
  src/Components/MovieDetails/MovieDetails.js
  src/Components/MoviePoster/MoviePoster.js
Labels: DOM, New component, enhancement

#9 Tdd/setup testing environment
  .eslintcache
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/MovieContainer/MovieContainer.js
  src/Components/MovieDetails/MovieDetails.js
  src/Components/MovieDetails/MovieDetails.test.js
  src/Components/MoviePoster/MoviePoster.js
  src/Components/MoviePoster/MoviePoster.test.js
Labels: TDD

#14 Rough out styling for Movie Detail view
  .eslintcache
  src/Components/App/App.js
  src/Components/MovieDetails/MovieDetails.css
  src/Components/MovieDetails/MovieDetails.js
Labels: DOM, enhancement

#15 Feature/api calls
  .eslintcache
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/MovieDetails/MovieDetails.css
  src/Components/MovieDetails/MovieDetails.js
  src/apiCalls.js
Labels: DOM, apiCalls, enhancement

#18 Testing Apicalls
  .eslintcache
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/MovieDetails/MovieDetails.js
  src/Components/MovieDetails/MovieDetails.test.js
  src/Components/MoviePoster/MoviePoster.test.js
Labels: apiCalls, enhancement

#19 Handling errors
  .eslintcache
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/MovieContainer/MovieContainer.test.js
  src/Components/MovieDetails/MovieDetails.test.js
  src/Components/MoviePoster/MoviePoster.test.js
Labels: TDD, apiCalls, enhancement

#26 Router setup and styling for links
  .eslintcache
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/MovieContainer/MovieContainer.js
  src/Components/MovieDetails/MovieDetails.css
  src/Components/MovieDetails/MovieDetails.js
  src/Components/MoviePoster/MoviePoster.js
  src/index.js
Labels: New component, Router, enhancement

#28 Feature/movie trailers
  .eslintcache
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/MovieDetails/MovieDetails.js
  src/apiCalls.js
Labels: DOM, enhancement

#30 Feature/testing react router
  .eslintcache
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/MovieContainer/MovieContainer.test.js
  src/Components/MovieDetails/MovieDetails.js
  src/Components/MovieDetails/MovieDetails.test.js
  src/Components/MoviePoster/MoviePoster.js
  src/Components/MoviePoster/MoviePoster.test.js
Labels: Router, TDD

#34 Stretch goals
  .eslintcache
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/MovieContainer/MovieContainer.js
  src/Components/Search/Search.css
  src/Components/Search/Search.js
  src/Components/Search/Search.test.js
Labels: DOM, New component, enhancement

#35 Search tests
  .eslintcache
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/Header/Header.js
  src/Components/Header/Header.test.js
  src/Components/MovieContainer/MovieContainer.test.js
  src/Components/Search/Search.js
  src/Components/Search/Search.test.js
Labels: New component, Router, TDD

#36 Add trailers to movie details via Carousel
  .eslintcache
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/Header/Header.js
  src/Components/MovieDetails/MovieDetails.js
  src/Components/MovieDetails/MovieDetails.test.js
Labels: TDD, apiCalls, enhancement

#37 Styling final touches
  .eslintcache
  package-lock.json
  package.json
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/MovieDetails/MovieDetails.css
  src/Components/MovieDetails/MovieDetails.js
  src/Components/MovieDetails/MovieDetails.test.js
  src/Components/MoviePoster/MoviePoster.css
  src/Components/MoviePoster/MoviePoster.js
  src/Components/MoviePoster/MoviePoster.test.js
Labels: DOM, TDD, enhancement
